### ISSUE TITLE
PYTHON_TASKS.md ошибка в разделе "Списки-и-работа-с-ними-срезки-генераторы"

### ISSUE THREAD

**Issue by DrSnail** [skhayrulin/python_course#4]
[Ошибка в этом разделе](https://github.com/skhayrulin/python_course/blob/master/PYTHON_TASKS.md#%D0%A1%D0%BF%D0%B8%D1%81%D0%BA%D0%B8-%D0%B8-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BD%D0%B8%D0%BC%D0%B8-%D1%81%D1%80%D0%B5%D0%B7%D0%BA%D0%B8-%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D1%8B) в самом конце
> Если вы хотите проверить находится ли элемент в списке удобно использовать оператор `is` 

На это

> Если вы хотите проверить находится ли элемент в списке удобно использовать оператор `in`

```
x = [1,2,3]
1 in x
>>>True
```

**Comment by skhayrulin** [comment]
@DrSnail cпасибо за ценное замечание, можете создать merge request с исправлением

**Comment by DrSnail** [comment]
> @DrSnail cпасибо за ценное замечание, можете создать merge request с исправлением

Да я бы и не против, но нет разрешения на пуши ¯\_(ツ)_/¯

**Comment by skhayrulin** [comment]
вы можете оформить pull request без разрешений этого репозитория, для этого вам нужно сделать [форк от проекта](https://help.github.com/articles/fork-a-repo/), внести изменения, и создать [pull request](https://help.github.com/articles/creating-a-pull-request/) из вашего репозитория в мой. Вроде так
